version: '1.1'
services:
  web-1:
    build: .
    volumes:
        - ./site:/var/www/html
    ports:
        - 80:80
  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : 1234
      MYSQL_DATABASE : docker_db
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80
    
